<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="3.687" timestamp="2025-10-30T13:14:23.848126" hostname="DESKTOP-AITNV0T"><testcase classname="" name="tests.unit.test_config_loader" time="0.000"><error message="collection failure">C:\Users\Fedor\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py:617: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
C:\Users\Fedor\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\pathlib.py:567: in import_path
    importlib.import_module(module_name)
C:\Users\Fedor\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py:88: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1387: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1360: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:1331: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:935: in _load_unlocked
    ???
C:\Users\Fedor\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\assertion\rewrite.py:177: in exec_module
    source_stat, co = _rewrite_test(fn, self.config)
C:\Users\Fedor\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\assertion\rewrite.py:359: in _rewrite_test
    tree = ast.parse(source, filename=strfn)
C:\Users\Fedor\AppData\Local\Programs\Python\Python313\Lib\ast.py:50: in parse
    return compile(source, filename, mode, flags,
E     File "E:\github\bioactivity_data_acquisition\tests\unit\test_config_loader.py", line 232
E       postprocess: {}
E                     ^
E   SyntaxError: f-string: valid expression required before '}'</error></testcase></testsuite></testsuites>